name: json-benchmark
version: 0.1.0.0
github: "githubuser/json-benchmark"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/json-benchmark#readme>

dependencies:
  - aeson <= 1.4.7.1
  - attoparsec <= 0.14.1
  - base >= 4.7 && < 5
  - bytestring <= 0.10.10.1
  - parsec <= 3.1.14.0
  - time <= 1.12
  - timeit <= 2.0

library:
  source-dirs: src

executables:
  json-benchmark-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - json-benchmark

tests:
  json-benchmark-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - json-benchmark
